// actionTypes.ts

// User Management Action Types
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const WALLET_SEEN_REQUEST = "WALLET_SEEN_REQUEST";
export const WALLET_SEEN_SUCCESS = "WALLET_SEEN_SUCCESS";
export const WALLET_SEEN_FAIL = "WALLET_SEEN_FAIL";

export const GET_NEW_WALLET_REQUEST = "GET_NEW_WALLET_REQUEST";
export const GET_NEW_WALLET_SUCCESS = "GET_NEW_WALLET_SUCCESS";
export const GET_NEW_WALLET_FAIL = "GET_NEW_WALLET_FAIL";

export const UPLOAD_PROFILE_IMAGE_REQUEST = "UPLOAD_PROFILE_IMAGE_REQUEST";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_FAIL = "UPLOAD_PROFILE_IMAGE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_VERIFY_OTP_REQUEST_AUTH =
  "FORGOT_PASSWORD_VERIFY_OTP_REQUEST_AUTH";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

// Authentication Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const VERIFY_OTP_REQUEST_AUTH = "VERIFY_OTP_REQUEST_AUTH";
export const VERIFY_OTP_SUCCESS_AUTH = "VERIFY_OTP_SUCCESS_AUTH";
export const VERIFY_OTP_FAIL_AUTH = "VERIFY_OTP_FAIL_AUTH";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAIL = "RESEND_OTP_FAIL";

// Assets Management Action Types
export const CHECK_IMAGE_REQUEST = "CHECK_IMAGE_REQUEST";
export const CHECK_IMAGE_SUCCESS = "CHECK_IMAGE_SUCCESS";
export const CHECK_IMAGE_FAIL = "CHECK_IMAGE_FAIL";

export const CREATE_ASSET_REQUEST = "CREATE_ASSET_REQUEST";
export const CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS";
export const CREATE_ASSET_FAIL = "CREATE_ASSET_FAIL";

export const SEARCH_ASSETS_REQUEST = "SEARCH_ASSETS_REQUEST";
export const SEARCH_ASSETS_SUCCESS = "SEARCH_ASSETS_SUCCESS";
export const SEARCH_ASSETS_FAIL = "SEARCH_ASSETS_FAIL";

// Settings Action Types
export const SET_SETTINGS_REQUEST = "SET_SETTINGS_REQUEST";
export const SET_SETTINGS_SUCCESS = "SET_SETTINGS_SUCCESS";
export const SET_SETTINGS_FAIL = "SET_SETTINGS_FAIL";

export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAIL = "GET_SETTINGS_FAIL";

export const UPDATE_SETTINGS_REQUEST = "UPDATE_SETTINGS_REQUEST";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAIL = "UPDATE_SETTINGS_FAIL";
export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const UPDATE_PASSWORD_SETTINGS_REQUEST = "UPDATE_PASSWORD_SETTINGS_REQUEST";

// Thread Action Types
export const CREATE_THREAD_REQUEST = "CREATE_THREAD_REQUEST";
export const DELETE_THREAD_REQUEST = "DELETE_THREAD_REQUEST";
export const CREATE_THREAD_Items_REQUEST = "CREATE_THREAD_Items_REQUEST";
export const GET_ALL_THREADS_REQUEST = "GET_ALL_THREADS_REQUEST"
export const GET_ALL_THREADSITEMS_REQUEST = "GET_ALL_THREADSITEMS_REQUEST"

// Transactions action types
export const FETCH_TRANSACTIONS_REQUEST = "FETCH_TRANSACTIONS_REQUEST";
export const FETCH_TRANSACTIONS_TOTALS_REQUEST = "FETCH_TRANSACTIONS_TOTALS_REQUEST";
